assetic:
    bundles:        [BCCCronManagerBundle]
    filters:
        phpcssembed: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
    assets:
        jquery_js:
            inputs:
                - '%kernel.root_dir%/../components/jquery/jquery.min.js'
        bootstrap_js:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js'
        bootstrap_less:
            inputs:
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less'
                - '%kernel.root_dir%/../vendor/twbs/bootstrap/less/responsive-utilities.less'
            filters: [lessphp,phpcssembed]
